webempresa/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name="blog"),
    path('category/<int:category_id>/', views.category, name="category"),
]

webempresa/contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact, name="contact"),
]

webempresa/core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('store/', views.store, name="store"),
]

webempresa/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:page_id>/', views.page, name="page"),
    
]

webempresa/services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.services, name="services"),
]

webempresa/webempresa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('services/', include('services.urls')),
    path('page/', include('pages.urls')),
    path('admin/', admin.site.urls),
    
    # Paths de pages
    path('contact/', include('contact.urls')),
]

from django.conf import settings

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

webempresa/blog/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "categoría"
        verbose_name_plural = "categorías"

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name="Título")
    content = RichTextField(blank=True, null=True, verbose_name="Contenido")
    published = models.DateTimeField(default=now, verbose_name="Fecha de publicación")
    image = models.ImageField(upload_to="images/", null=True, blank=True, verbose_name="Imagen")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Autor")
    categories = models.ManyToManyField(Category, verbose_name="Categorías", related_name="get_posts")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")    

    class Meta:
        verbose_name = "entrada"
        verbose_name_plural = "entradas"

    def __str__(self):
        return self.title

    

webempresa/contact/models.py
from django.db import models

# Create your models here.

webempresa/core/models.py
from django.db import models

# Create your models here.

webempresa/pages/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Page(models.Model):
    title = models.CharField(max_length=200, verbose_name="Título")
    content = RichTextField(verbose_name="Contenido")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    ordering = ['order','title']
    
    
    class Meta:
        verbose_name = "página"
        verbose_name_plural = "páginas"
        ordering = ['title']

    def __str__(self):
        return self.title
    

webempresa/services/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.add()
class Service(models.Model):
    title = models.CharField(max_length=200, verbose_name="Título")
    subtitle = models.CharField(max_length=200, verbose_name="Subtítulo")
    content = RichTextField(blank=True, null=True, verbose_name="Contenido")
    image = models.ImageField(upload_to="images/", blank=True, null=True, verbose_name = 'Imagen')
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Servicio"
        verbose_name_plural = "Servicios"
        ordering = ['-created']

    def __str__(self):
        return self.title

webempresa/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label="Nombre", min_length = 3, max_length = 100, required=True,
            widget=forms.TextInput(attrs={'placeholder': 'Escribe tu Nombre', 'class': 'form-control'}))
    email = forms.EmailField(label="Email", min_length = 3, max_length = 100, required=True,
            widget=forms.TextInput(attrs={'placeholder': 'Escribe tu Email', 'class': 'form-control'}))
    content = forms.CharField(label="Contenido", min_length = 10, max_length = 1000, required=True,
            widget=forms.Textarea(attrs={'placeholder': 'Escribe tu Mensaje', 'rows': 3, 'class': 'form-control'}))

webempresa/blog/views.py
from django.shortcuts import render,  get_object_or_404
from .models import Post, Category

def blog(request):
    posts = Post.objects.all()
    return render(request, "blog/blog.html", {'posts':posts})

def category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    return render(request, "blog/category.html", {'category':category})

webempresa/contact/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.models import User        
from django.contrib.auth import login, authenticate, logout  
from django.conf import settings  
from django.core.mail import send_mail 
from webempresa.settings import EMAIL_HOST_USER 
from .forms import ContactForm

def contact(request):
    contact_form = ContactForm
    return render(request, "contact/contact.html", {'form': contact_form})

def signup(request):
    if request.method=="POST":
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        
        user = User.objects.create_user(
            username = username,
            password = password,
            email = email
        )
        
        login(request, user)
        subject = 'Bienvenido a LENOTECA'
        message = f'Hola {user.username}, Gracias por Contactarnos.'
        email_from = settings.EMAIL_HOST_USER 
        recipient_list = [user.email,]
        send_mail(subject, message, email_from, recipient_list)
        return redirect('/contact/')
    
    return render(request, 'contact.html' )

webempresa/core/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
    return render(request, "core/home.html")

def about(request):
    return render(request, "core/about.html")

def store(request):
    return render(request, "core/store.html")

webempresa/pages/views.py
from django.shortcuts import render, get_object_or_404
from .models import Page

# Create your views here.
def page(request, page_id):
    page = get_object_or_404(Page, id=page_id)
    return render(request, 'pages/sample.html', {'page':page})

webempresa/services/views.py
from django.shortcuts import render
from .models import Service

def services(request):
    services = Service.objects.all()
    return render(request, "services/services.html", {'services': services})

webempresa/blog/templates/blog/blog.html
{% extends 'core/base.html' %}
{% block title %}{{category}}{% endblock %}


{% block content %}
{% for post in posts %}
{% load static %}
<section class="page-section cta">
    <div class="container_blog">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-innerv text-center rounded">
                    <div class="left_cta_innerv">
                        <h2 class="section-heading mb-5">
                            <span class="section-heading-lower">{{post.title}}</span>
                        </h2>
                        <p class="mb-0">
                            <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{post.image.url}}" alt="">
                        </p>
                    </div>
                    <div class="rigth_cta_innerv">
                        <p class="mb-0 mbt">
                            {{post.content|linebreaks}}
                        </p>
                        <p class="mb-0 mbt">
                            <!--
                            <span class="section-heading-under">
                                Publicado por <em><b>{{post.author}}</b></em>
                                en <em>{{post.categories.all|join:", "}}</em>
                            </span>
                            -->
                            
                            <span class="section-heading-under">
                                Publicado por <em><b>{{post.author}}</b></em> en
                                {% for category in post.categories.all %}
                                    <a href="{% url 'category' category.id %}" class="link"> {{category.name}}</a>
                                {% endfor %}
                            </span>
                            
                        </p>
                        <span class="section-heading-upper">
                            {{post.published|date:"SHORT_DATE_FORMAT"}}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endfor %}
{% endblock %}

webempresa/blog/templates/blog/category.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}{{category}}{% endblock %}

{% block content %}
    {% for post in posts %}
    <section class="page-section cta">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-innerv text-center rounded">
                    <h2 class="section-heading mb-5">
                        <span class="section-heading-upper">
                            {{post.published}}</span>
                        <span class="section-heading-lower">
                            {{post.title}}</span>
                    </h2>
                    <p class="mb-0">
                        <img class="mx-auto d-flex img-fluid mb-3 mb-lg-0" 
                            src="{{post.image.url}}" alt="">
                    </p>
                    <p class="mb-0 mbt">{{post.content}}</p>
                    <p class="mb-0 mbt">
                        <span class="section-heading-under">
                            Publicado por <em><b>{{post.author}}</b></em> en
                            {% for category in post.categories.all %}
                                <a href="{% url 'category' category.id %}" class="link"> {{category.name}}</a>
                            {% endfor %}
                        </span>
                    </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}
{% endblock %}

webempresa/contact/templates/contact/contact.html
{% extends 'core/base.html' %}
{% block title %} Contact {% endblock %}

{% block content %}
{% load static %}
<section class="page-section-contact about-heading">
    <div class="container_contact">
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/img/S1.jpg' %}" alt="">
        <div class="about-heading-content">
                <div class="row-contact">
                    <div class="col-xl-9 col-lg-10 mx-auto">
                        <div class="bg-faded rounded p-5 contact_form">
                            <h2 class="section-heading mb-4">
                                <span class="section-heading-upper">Envíanos tus dudas</span>
                                <span class="section-heading-lower">Contacto</span>
                            </h2>
                            <!-- Formulario de contacto -->
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="label-contact"><b>Nombre *</b></label>
                                    <div class="input-group">{{form.name}}</div>
                                    {{form.name.errors}}
                                </div>
                                <div class="form-group">
                                    <label class="label-contact"><b>Email *</b></label>
                                    <div class="input-group">{{form.email}}</div>
                                    {{form.email.errors}}
                                </div>
                                <div class="form-group">
                                    <label class="label-contact"><b>Mensaje *</b></label>
                                    <div class="input-group">{{form.content}}</div>
                                    {{form.content.errors}}
                                </div>
                                <div class="text-center">
                                    <input type="submit" class="btn-contact" value="Enviar">
                                </div>
                            </form>
                            {{request.POST}}

                            <!--
                            <form action="" method="POST">
                                <input type="hidden" name="csrfmiddlewaretoken" value="lut431ADLvkofX1A9UgQKLAAm4GHsi1S3jonkSTAdwwM76w9AzNUhvnnm7LLLmgG">
                                <div class="form-group">
                                    <label>Nombre *</label>
                                    <div class="input-group">
                                        <input type="text" name="name" class="form-control" placeholder="Escribe tu nombre" maxlength="100" minlength="3" required id="id_name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Email *</label>
                                    <div class="input-group">
                                        <input type="email" name="email" class="form-control" placeholder="Escribe tu email" maxlength="100" minlength="3" required id="id_email">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Mensaje *</label>
                                    <div class="input-group">
                                        <textarea name="content" cols="40" rows="3" class="form-control" placeholder="Escribe tu mensaje" maxlength="1000" minlength="10" required id="id_content"></textarea>
                                    </div>
                                </div>
                                <div class="text-center">
                                    <input type="submit" class="btn-contact btn-primary btn-block py-2" value="Enviar">
                                </div>
                            </form>
                            -->
                            <!-- Fin formulario de contacto -->
                        </div>
                    </div>
                </div>
        </div>
    </div>
</section>

{% endblock %}

webempresa/core/templates/core/about.html
{% extends 'core/base.html' %}
{% block title %} About {% endblock %}

{% block content %}
{% load static %}
<section class="page-section-about about-heading">
    <div class="container_about">
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/img/vinateria.jpg' %}" alt="">
    </div>
    <div class="about-heading-content">
        <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
                <div class="bg-faded rounded p-5">
                    <h2 class="section-heading mb-4">
                        <span class="section-heading-upper">Tradición familiar italiana</span>
                        <span class="section-heading-lower">Nuestra historia</span>
                    </h2>
                    <p>L'enoteca Vinateria nació hace más de 15 años en CABA -Argentina, cuando Juan Bimba, después de trabajar más de una década en un negocio familiar dedicado al vino, decidió iniciar su propio negocio.</p>
                    <p> En 1998 abría una tienda de poco más de 80 m2, la cual servía para la venta al por menor, al por mayor y la distribución. Con el tiempo el proyecto se fue ampliando, primero con un almacén de 400 m2,
                        después con el traslado de la tienda a otra más grande, en 2012 con la creación de L'enoteca.com y finalmente, a principios del 2015, ampliando las Sucursales en diferentes Barrios de la Ciudad.</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

webempresa/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %} | L'enoteca</title>

        {% load static %}
        <!-- Fuentes -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
        <link rel="icon" type="image/x-icon" href="{% static 'core/img/django.jpg' %}">
        <!-- Estilos -->
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'core/css/estilos.css' %}" rel="stylesheet">
</head>
<body>
    <div class="encabezado">
        <h1 class="site-heading text-center text-white d-none d-lg-block">
            <span class="site-heading-upper text-primary mb-3">I migliori vini italiani</span>
            <span class="site-heading-lower">L'enoteca</span>
        </h1>
    
        <!-- Navegación -->
        <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
            <div class="container">
                <!-- 
                <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="/">La Caffettiera</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                -->
                <div class="menu navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item px-lg-4 active">
                            <a class="nav-link text-uppercase text-expanded" href="{% url 'home' %}">Inicio</a>
                        </li>
                        <li class="nav-item px-lg-4 ">
                            <a class="nav-link text-uppercase text-expanded" href="{% url 'about' %}">Historia</a>
                        </li>
                        <li class="nav-item px-lg-4 ">
                            <a class="nav-link text-uppercase text-expanded" href="{% url 'services' %}">Servicios</a>
                        </li>
                        <li class="nav-item px-lg-4 ">
                            <a class="nav-link text-uppercase text-expanded" href="{% url 'store' %}">Visítanos</a>
                        </li>
                        <li class="nav-item px-lg-4 ">
                            <a class="nav-link text-uppercase text-expanded" href="{% url 'contact' %}">Contacto</a>
                        </li>
                        <li class="nav-item px-lg-4"> 
                            <a class="nav-link text-uppercase text-expanded" href="{% url 'blog' %}">Blog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <!-- Contenido -->

    {% block content %} {% endblock %}

    <!-- Pié de página -->
    <footer class="footer text-faded text-center py-5">
        <div class="container-footer">
            <p class="registro">&copy; José Luis Galvis - Full Stack Developer - 2023 </p>
            <p class="m-0">
                <a href="https://twitter.com/" class="link">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
                <a href="http://facebook.com" class="link">
                <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                </span>
                </a>
                <a href="http://instagram.co" class="link">
                <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                </span>
                </a>
            </p>
            <p class="m-0 mbt">
                {% load pages_extras %}
                {% get_page_list as page_list %}
                {% for page in page_list %}
                    <a href="{% url 'page' page.id %}" class="link">{{page.title}}</a> 
                    {% if not forloop.last %}·{% endif %} 
                {% endfor %}
            </p>

            <p class="m-0 mbt1"> L'enoteca 2020</p>
        </div>
    </footer>

    <!-- Bootstrap -->
    <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

webempresa/core/templates/core/home.html
{% extends 'core/base.html' %}
{% block title %} Home {% endblock %}

{% block content %}
{% load static %}
    <!-- Cabecera -->
    <section class="page-section-home clearfix">
        <div class="container-home">
            <div class="intro">
                <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'core/img/4E.jpg' %}" alt="">
                <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                    <h2 class="section-heading mb-4">
                    <span class="section-heading-upper">Déjate sorprender</span>
                    <span class="section-heading-lower">Te gustará</span>
                    </h2>
                    <p class="mb-3">Trabajamos sólo con las mejores marcas. Una vez lo pruebes, nuestro Vino será la mejor forma de empezar tu Fin de Semana.
                    </p>
                    <div class="intro-button mx-auto">
                        <a class="btn btn-primary btn-xl" href="{% url 'store' %}">Visítanos</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

webempresa/core/templates/core/store.html
{% extends 'core/base.html' %}
{% block title %} Store {% endblock %}

{% block content %}
{% load static %}
<section class="page-section cta">
    <div class="container_store">
        <div class="row">
            <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
                <h2 class="section-heading mb-5">
                <span class="section-heading-upper">Te esperamos</span>
                <span class="section-heading-lower">Visítanos</span>
                </h2>
                <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
                <li class="list-unstyled-item list-hours-item d-flex">
                    Lunes a viernes
                    <span class="ml-auto">7:00 a 20:00</span>
                </li>
                <li class="list-unstyled-item list-hours-item d-flex">
                    Sábados
                    <span class="ml-auto">9:00 a 17:00</span>
                </li>
                <li class="list-unstyled-item list-hours-item d-flex">
                    Domingos
                    <span class="ml-auto">Cerrado</span>
                </li>
                </ul>
                <p class="address mb-5">
                <em>
                    <strong>Av. San Juan <br> Barrio San Cristobal 2510</strong>
                    <br>
                    CABA - Argentina
                </em>
                </p>
                <p class="mb-0">
                <small>
                    <em>Llámanos y pregunta</em>
                </small>
                <br>
                (11) 5555 5678
                </p>
            </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

webempresa/pages/templates/pages/sample.html
{% extends 'core/base.html' %}
{% block title %}{{page.title}}{% endblock %}

{% block content %}
{% load static %}
<section class="page-section-pages about-heading">
    <div class="container_pages">
        <div class="about-heading-content mbtm">
            <div class="row">
                <div class="col-xl-9 col-lg-10 mx-auto">
                    <div class="bg-faded rounded p-5 forced">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-lower">
                                {{page.title}}</span>
                        </h2>
                        <br>
                        <div class="section-content">
                            {{page.content|safe}}
                            {% if user.is_authenticated %}
                                <p><a href="#">Editar</a></p>
                            {% endif %}
                        </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

webempresa/services/templates/services/services.html
{% extends 'core/base.html' %}
{% block title %} Services {% endblock %}

{% block content %}
{% for service in services reversed %}
{% load static %}
<section class="page-section-service">
    <div class="container_service">
        <div class="product-item">
            <div class="product-item-title d-flex">
                <div class="bg-faded p-5 d-flex mr-auto rounded">
                    <h2 class="section-heading mb-0">
                        <span class="section-heading-upper">{{ service.subtitle }}</span>
                        <span class="section-heading-lower">{{ service.title }}</span>
                    </h2>
                </div>
            </div>
            <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{ service.image.url }}" alt="">
            <div class="product-item-description d-flex ml-auto">
                <div class="bg-faded p-5 rounded">
                    <p class="mb-0">{{ service.content }}</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endfor %}
{% endblock %}